### ISSUE TITLE
systemd-ukify version error

### ISSUE THREAD

**Issue by unforgivablesin** [systemd/particleos#15]
The title says it. When I try to build ParticleOS, the systemd steps in the repository, or when I use `ToolsTree=default` in `[Build]` in my mkosi.conf. I get the same error.

```bash
Removed '/buildroot/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service'.
Created symlink '/buildroot/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service' \u2192 '/usr/lib/systemd/system/systemd-homed-activate.service'.
Created symlink '/buildroot/etc/systemd/system/basic.target.wants/rpmdb-migrate.service' \u2192 '/usr/lib/systemd/system/rpmdb-migrate.service'.
Created symlink '/buildroot/etc/systemd/system/basic.target.wants/rpmdb-rebuild.service' \u2192 '/usr/lib/systemd/system/rpmdb-rebuild.service'.
Created symlink '/buildroot/etc/systemd/system/multi-user.target.wants/machines.target' \u2192 '/usr/lib/systemd/system/machines.target'.
\u2023  Generating hardware database
\u2023  Removing files\u2026
\u2023 Could not rename /var/tmp/mkosi-workspace-pze_puux/staging/tools to /var/home/user/Desktop/particleos/mkosi.output/tools as they are located on different devices, falling back to copying
Create snapshot of '/work/var/tmp/mkosi-workspace-pze_puux/staging/tools' in '/work/var/home/user/Desktop/particleos/mkosi.output/tools'
\u2023  /var/home/user/Desktop/particleos/mkosi.output/tools size is 985.0M.
\u2023 Found '/usr/bin/ukify' with version 255.14-1.fc40 but version 257~devel or newer is required to add unified kernel image profiles.
\u2023 (Use ToolsTree=default to get a newer version of 'ukify'.)
```

What should I do?

**Comment by DaanDeMeyer** [comment]
Documented in readme: https://github.com/systemd/particleos?tab=readme-ov-file#building-systemd-from-source

**Comment by unforgivablesin** [comment]
Yes. Like said in the issue, I did this but this is the error I get.

**Comment by DaanDeMeyer** [comment]
> Is there maybe other instructions I need to follow then? I did exactly this
> 
> ```shell
> git clone https://github.com/systemd/systemd
> cd systemd
> mkosi -t none
> ```
> 
> I got the error on the last command. I am on Fedora 41.

Try again with latest mkosi from git I merged a commit that should fix this

**Comment by unforgivablesin** [comment]
Now I am getting this:

```bash
>>> Curl error (52): Server returned nothing (no headers, no data) for http://mirroronet.pl/pub/mirrors/fedora/linux/development/rawhide/Everything/x86_64/os/Packages
>>> Status code: 404 for https://mirroronet.pl/pub/mirrors/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d
>>> Status code: 404 for https://b4sh.mm.fcix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc4
>>> Status code: 404 for http://b4sh.mm.fcix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc42
>>> Status code: 404 for http://fedora.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7
>>> Status code: 404 for http://mirror.telepoint.bg/fedora/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc42.x8
>>> Status code: 404 for https://mirror.telepoint.bg/fedora/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc42.x
>>> Status code: 404 for https://level66.mm.fcix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.
>>> Status code: 404 for http://level66.mm.fcix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.f
>>> Status code: 404 for https://fr2.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.1
>>> Status code: 404 for http://fr2.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10
>>> Status code: 404 for https://mirrors.n-ix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc4
>>> Status code: 404 for http://mirrors.n-ix.net/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc42
>>> No more mirrors to try - All mirrors were already tried without success
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
[242/242] Total                                                                                                               100% |   0.0   B/s |   0.0   B |  00m00sFailed to download packages
 Librepo error: Cannot download Packages/b/bpftool-6.13.0-0.rc0.20241126git7eef7e306d3c.10.fc42.x86_64.rpm: All mirrors were tried
\u2023 "/work/prepare final" returned non-zero exit code 123.
```

I am unsure if its me or not, I dont think so tho. Thoughts?

**Comment by unforgivablesin** [comment]
This command fixes the issue.

```bash
mkosi -t none -ff
```

**Comment by wackywobblewave** [comment]
> Passing `--profile obs` to mkosi (or setting `Profiles=obs` in your local mkosi conf) should work

i did. still getting the systemd-ukify version error. (mkosi from git)
